=== yermochenko/epam-2021-example-02/accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://epam.vsu.by/final-project-example/accounts" xmlns:tns="http://epam.vsu.by/final-project-example/accounts" elementFormDefault="qualified">
    <element name="accounts">
        <complexType>
            <sequence>
                <element name="account" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="id" type="positiveInteger"/>
                            <element name="name" type="string"/>
                            <element name="balance" type="nonNegativeInteger"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== yermochenko/epam-2021-example-02/accounts.xml
<?xml version="1.0" encoding="UTF-8"?><accounts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://epam.vsu.by/final-project-example/accounts" xsi:schemaLocation="http://epam.vsu.by/final-project-example/accounts accounts.xsd"><account><id>1</id><name>Иванов</name><balance>1234</balance></account><account><id>2</id><name>Петров</name><balance>11111</balance></account></accounts>
