=== yermochenko/epam-2021-example-02/transfers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://epam.vsu.by/final-project-example/transfers" xmlns:tns="http://epam.vsu.by/final-project-example/transfers" elementFormDefault="qualified">
    <element name="transfers">
        <complexType>
            <sequence>
                <element name="transfer" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="id" type="positiveInteger"/>
                            <element name="source-account-id" type="positiveInteger" minOccurs="0"/>
                            <element name="destination-account-id" type="positiveInteger" minOccurs="0"/>
                            <element name="summ" type="positiveInteger"/>
                            <element name="date" type="dateTime"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== yermochenko/epam-2021-example-02/transfers.xml
<?xml version="1.0" encoding="UTF-8"?><transfers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://epam.vsu.by/final-project-example/transfers" xsi:schemaLocation="http://epam.vsu.by/final-project-example/transfers transfers.xsd"><transfer><id>1</id><destination-account-id>1</destination-account-id><summ>13579</summ><date>2021-08-16T14:09:43</date></transfer><transfer><id>2</id><source-account-id>1</source-account-id><destination-account-id>2</destination-account-id><summ>12345</summ><date>2021-08-16T14:17:45</date></transfer><transfer><id>3</id><source-account-id>2</source-account-id><summ>1234</summ><date>2021-08-16T14:18:17</date></transfer></transfers>
